<a href="https://colab.research.google.com/github/Deveshjd/ML-Notebooks/blob/main/pandas_df.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
s = pd.Series(range(1,10))
s

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64

In [ ]:
s.max()

9

In [ ]:
s.argmax() # returns the index of the maximum no. i.e. 9's index value which is 8

np.int64(8)

In [ ]:
s1 = pd.Series([2,3,5,2,1,43,4], index = ['a','b','c','d','e','f','g'])
s1

a     2
b     3
c     5
d     2
e     1
f    43
g     4
dtype: int64

In [ ]:
s1['h'] = 12

In [ ]:
s1

a     2
b     3
c     5
d     2
e     1
f    43
g     4
h    12
dtype: int64

# Dataframe


*   2d
*   collecions of series
*   can store multiple types of data(Heterogeneous)

In [ ]:
df = pd.DataFrame({
    "Name" : ["Dj", "Rj", "Vp", "Rs", "Hk"],
    "Age" : [23,34,45,34,"23"],
    # "Branch" : ["cse", "cse", "ai"] #--> this will show the error because the size must be equal
    "Sex" : ["M", "M", "M", "F", "M"]
})

In [ ]:
df

  Name Age Sex
0   Dj  23   M
1   Rj  34   M
2   Vp  45   M
3   Rs  34   F
4   Hk  23   M

**We can create dataframe in 2 ways... either by creating a dictionary or by using list of lists**
1.  using dictionary --> pd.DataFrame({"key" : [values]})
2.  using list of lists --> pd.DataFrame([ [row 1],
                                          [row 2] ], columns = [col names])

In [ ]:
df1 = pd.DataFrame([
    ["Dj", 23, "M"],
    ["Rj", 34, "M"],
    ["Vp", 45, "M"],
    ["Rs", 34, "F"],
    ["Hk", 23, "M"]],
    columns=["Name", "Age", "Sex"]
)

In [ ]:
df1

  Name  Age Sex
0   Dj   23   M
1   Rj   34   M
2   Vp   45   M
3   Rs   34   F
4   Hk   23   M

In [ ]:
df2 = pd.DataFrame({
    "Name" : ["Dj", "Rj", "Vp", "Rs", "Hk"],
    "Age" : np.random.randint(20,40, 5),
    "Sex" : ["M", "M", "M", "F", "M"],
    "Marks" : np.random.normal(40,10,5),
    "Salary" : np.random.normal(100000,5000,5).astype(int),
    "Weight" : np.random.randint(50,100,5)
})

In [ ]:
df2

  Name  Age Sex      Marks  Salary  Weight
0   Dj   20   M  39.199686  104969      57
1   Rj   30   M  40.224257   96197      86
2   Vp   35   M  21.119038   98669      59
3   Rs   26   F  22.282173   95726      76
4   Hk   39   M  31.582758  103740      65

In [ ]:
df2["Sex"] = np.random.choice(["Male", "Female"], 5)

In [ ]:
df2

  Name  Age     Sex      Marks  Salary  Weight
0   Dj   20    Male  39.199686  104969      57
1   Rj   30    Male  40.224257   96197      86
2   Vp   35  Female  21.119038   98669      59
3   Rs   26  Female  22.282173   95726      76
4   Hk   39    Male  31.582758  103740      65

In [ ]:
df2["Weight"]

0    57
1    86
2    59
3    76
4    65
Name: Weight, dtype: int64

In [ ]:
df2[df2["Salary"] > 98000]

  Name  Age     Sex      Marks  Salary  Weight
0   Dj   20    Male  39.199686  104969      57
2   Vp   35  Female  21.119038   98669      59
4   Hk   39    Male  31.582758  103740      65

In [ ]:
df2["Bonus"] = df2["Salary"]*0.2

In [ ]:
df2

  Name  Age     Sex      Marks  Salary  Weight    Bonus
0   Dj   20    Male  39.199686  104969      57  20993.8
1   Rj   30    Male  40.224257   96197      86  19239.4
2   Vp   35  Female  21.119038   98669      59  19733.8
3   Rs   26  Female  22.282173   95726      76  19145.2
4   Hk   39    Male  31.582758  103740      65  20748.0

In [ ]:
df2["After bonus"] = df2["Salary"] + df2["Bonus"]

In [ ]:
df2

  Name  Age     Sex      Marks  Salary  Weight    Bonus  After bonus
0   Dj   20    Male  39.199686  104969      57  20993.8     125962.8
1   Rj   30    Male  40.224257   96197      86  19239.4     115436.4
2   Vp   35  Female  21.119038   98669      59  19733.8     118402.8
3   Rs   26  Female  22.282173   95726      76  19145.2     114871.2
4   Hk   39    Male  31.582758  103740      65  20748.0     124488.0

In [ ]:
df2.describe()

,Age,Marks,Salary,Weight,Bonus,After bonus
count,5.000000,5.000000,5.00000,5.000000,5.000000,5.000000
mean,30.000000,30.881582,99860.20000,68.600000,19972.040000,119832.240000
std,7.449832,9.030852,4274.40893,12.218838,854.881786,5129.290716
min,20.000000,21.119038,95726.00000,57.000000,19145.200000,114871.200000
25%,26.000000,22.282173,96197.00000,59.000000,19239.400000,115436.400000
50%,30.000000,31.582758,98669.00000,65.000000,19733.800000,118402.800000
75%,35.000000,39.199686,103740.00000,76.000000,20748.000000,124488.000000
max,39.000000,40.224257,104969.00000,86.000000,20993.800000,125962.800000

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         5 non-null      object
 1   Age          5 non-null      int64
 2   Sex          5 non-null      object
 3   Marks        5 non-null      float64
 4   Salary       5 non-null      int64
 5   Weight       5 non-null      int64
 6   Bonus        5 non-null      float64
 7   After bonus  5 non-null      float64
dtypes: float64(3), int64(3), object(2)
memory usage: 452.0+ bytes