<a href="https://colab.research.google.com/github/Deveshjd/ML-Notebooks/blob/main/TIps_data_(from_seaborn).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns

In [ ]:
data = sns.load_dataset("tips")

In [ ]:
data.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
data.groupby("day")["total_bill"].mean()

/tmp/ipykernel_427/3098308559.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  data.groupby("day")["total_bill"].mean()

day
Thur    17.682742
Fri     17.151579
Sat     20.441379
Sun     21.410000
Name: total_bill, dtype: float64

In [ ]:
data.groupby("day")[["total_bill", "tip", "size"]].mean()

/tmp/ipykernel_427/3697198241.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  data.groupby("day")[["total_bill", "tip", "size"]].mean()

      total_bill       tip      size
day
Thur   17.682742  2.771452  2.451613
Fri    17.151579  2.734737  2.105263
Sat    20.441379  2.993103  2.517241
Sun    21.410000  3.255132  2.842105

In [ ]:
data.groupby("day")[["total_bill", "tip", "size"]].agg({
    "total_bill" : "mean",
    "tip" : "sum",
    "size" : ["count", "sum"]
})

/tmp/ipykernel_427/2939273057.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  data.groupby("day")[["total_bill", "tip", "size"]].agg({

     total_bill     tip  size
           mean     sum count  sum
day
Thur  17.682742  171.83    62  152
Fri   17.151579   51.96    19   40
Sat   20.441379  260.40    87  219
Sun   21.410000  247.39    76  216

# Pivot Table

In [ ]:
data.pivot_table(index = "day", values = "total_bill")

/tmp/ipykernel_427/741507938.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  data.pivot_table(index = "day", values = "total_bill")

      total_bill
day
Thur   17.682742
Fri    17.151579
Sat    20.441379
Sun    21.410000

In [ ]:
data.pivot_table(index = "sex", values = "total_bill", columns="day")

/tmp/ipykernel_427/3643644754.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  data.pivot_table(index = "sex", values = "total_bill", columns="day")

day          Thur        Fri        Sat        Sun
sex
Male    18.714667  19.857000  20.802542  21.887241
Female  16.715312  14.145556  19.680357  19.872222

In [ ]:
df = sns.load_dataset("flights")

In [ ]:
df

     year month  passengers
0    1949   Jan         112
1    1949   Feb         118
2    1949   Mar         132
3    1949   Apr         129
4    1949   May         121
..    ...   ...         ...
139  1960   Aug         606
140  1960   Sep         508
141  1960   Oct         461
142  1960   Nov         390
143  1960   Dec         432

[144 rows x 3 columns]

In [ ]:
df.pivot_table(index = "year", values = "passengers", columns = "month")

/tmp/ipykernel_427/2036618813.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(index = "year", values = "passengers", columns = "month")

month,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec
year,,,,,,,,,,,,
1949,112.0,118.0,132.0,129.0,121.0,135.0,148.0,148.0,136.0,119.0,104.0,118.0
1950,115.0,126.0,141.0,135.0,125.0,149.0,170.0,170.0,158.0,133.0,114.0,140.0
1951,145.0,150.0,178.0,163.0,172.0,178.0,199.0,199.0,184.0,162.0,146.0,166.0
1952,171.0,180.0,193.0,181.0,183.0,218.0,230.0,242.0,209.0,191.0,172.0,194.0
1953,196.0,196.0,236.0,235.0,229.0,243.0,264.0,272.0,237.0,211.0,180.0,201.0
1954,204.0,188.0,235.0,227.0,234.0,264.0,302.0,293.0,259.0,229.0,203.0,229.0
1955,242.0,233.0,267.0,269.0,270.0,315.0,364.0,347.0,312.0,274.0,237.0,278.0
1956,284.0,277.0,317.0,313.0,318.0,374.0,413.0,405.0,355.0,306.0,271.0,306.0
1957,315.0,301.0,356.0,348.0,355.0,422.0,465.0,467.0,404.0,347.0,305.0,336.0
1958,340.0,318.0,362.0,348.0,363.0,435.0,491.0,505.0,404.0,359.0,310.0,337.0
1959,360.0,342.0,406.0,396.0,420.0,472.0,548.0,559.0,463.0,407.0,362.0,405.0
1960,417.0,391.0,419.0,461.0,472.0,535.0,622.0,606.0,508.0,461.0,390.0,432.0

In [ ]:
df.pivot_table(index = "year", values = "passengers", columns = "month", margins=True)

/tmp/ipykernel_427/1827957882.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(index = "year", values = "passengers", columns = "month", margins=True)

month,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec,All
year,,,,,,,,,,,,,
1949,112.00,118.0,132.000000,129.000000,121.000000,135.000000,148.000000,148.000000,136.000000,119.000000,104.000000,118.000000,126.666667
1950,115.00,126.0,141.000000,135.000000,125.000000,149.000000,170.000000,170.000000,158.000000,133.000000,114.000000,140.000000,139.666667
1951,145.00,150.0,178.000000,163.000000,172.000000,178.000000,199.000000,199.000000,184.000000,162.000000,146.000000,166.000000,170.166667
1952,171.00,180.0,193.000000,181.000000,183.000000,218.000000,230.000000,242.000000,209.000000,191.000000,172.000000,194.000000,197.000000
1953,196.00,196.0,236.000000,235.000000,229.000000,243.000000,264.000000,272.000000,237.000000,211.000000,180.000000,201.000000,225.000000
1954,204.00,188.0,235.000000,227.000000,234.000000,264.000000,302.000000,293.000000,259.000000,229.000000,203.000000,229.000000,238.916667
1955,242.00,233.0,267.000000,269.000000,270.000000,315.000000,364.000000,347.000000,312.000000,274.000000,237.000000,278.000000,284.000000
1956,284.00,277.0,317.000000,313.000000,318.000000,374.000000,413.000000,405.000000,355.000000,306.000000,271.000000,306.000000,328.250000
1957,315.00,301.0,356.000000,348.000000,355.000000,422.000000,465.000000,467.000000,404.000000,347.000000,305.000000,336.000000,368.416667
1958,340.00,318.0,362.000000,348.000000,363.000000,435.000000,491.000000,505.000000,404.000000,359.000000,310.000000,337.000000,381.000000
1959,360.00,342.0,406.000000,396.000000,420.000000,472.000000,548.000000,559.000000,463.000000,407.000000,362.000000,405.000000,428.333333
1960,417.00,391.0,419.000000,461.000000,472.000000,535.000000,622.000000,606.000000,508.000000,461.000000,390.000000,432.000000,476.166667
All,241.75,235.0,270.166667,267.083333,271.833333,311.666667,351.333333,351.083333,302.416667,266.583333,232.833333,261.833333,280.298611

In [ ]:
df.pivot_table(index = "year", values = "passengers", columns = "month", aggfunc = "sum", margins = True)

/tmp/ipykernel_427/1200923737.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(index = "year", values = "passengers", columns = "month", aggfunc = "sum", margins = True)

month,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec,All
year,,,,,,,,,,,,,
1949,112,118,132,129,121,135,148,148,136,119,104,118,1520
1950,115,126,141,135,125,149,170,170,158,133,114,140,1676
1951,145,150,178,163,172,178,199,199,184,162,146,166,2042
1952,171,180,193,181,183,218,230,242,209,191,172,194,2364
1953,196,196,236,235,229,243,264,272,237,211,180,201,2700
1954,204,188,235,227,234,264,302,293,259,229,203,229,2867
1955,242,233,267,269,270,315,364,347,312,274,237,278,3408
1956,284,277,317,313,318,374,413,405,355,306,271,306,3939
1957,315,301,356,348,355,422,465,467,404,347,305,336,4421
1958,340,318,362,348,363,435,491,505,404,359,310,337,4572
1959,360,342,406,396,420,472,548,559,463,407,362,405,5140
1960,417,391,419,461,472,535,622,606,508,461,390,432,5714
All,2901,2820,3242,3205,3262,3740,4216,4213,3629,3199,2794,3142,40363

In [ ]:
df.pivot_table(index="year", values="passengers", aggfunc="min")

      passengers
year
1949         104
1950         114
1951         145
1952         171
1953         180
1954         188
1955         233
1956         271
1957         301
1958         310
1959         342
1960         390

In [ ]:
data

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
d1 = data[:101]
d1

     total_bill   tip     sex smoker  day    time  size
0         16.99  1.01  Female     No  Sun  Dinner     2
1         10.34  1.66    Male     No  Sun  Dinner     3
2         21.01  3.50    Male     No  Sun  Dinner     3
3         23.68  3.31    Male     No  Sun  Dinner     2
4         24.59  3.61  Female     No  Sun  Dinner     4
..          ...   ...     ...    ...  ...     ...   ...
96        27.28  4.00    Male    Yes  Fri  Dinner     2
97        12.03  1.50    Male    Yes  Fri  Dinner     2
98        21.01  3.00    Male    Yes  Fri  Dinner     2
99        12.46  1.50    Male     No  Fri  Dinner     2
100       11.35  2.50  Female    Yes  Fri  Dinner     2

[101 rows x 7 columns]

In [ ]:
d2 = data[101:]
d2

     total_bill   tip     sex smoker   day    time  size
101       15.38  3.00  Female    Yes   Fri  Dinner     2
102       44.30  2.50  Female    Yes   Sat  Dinner     3
103       22.42  3.48  Female    Yes   Sat  Dinner     2
104       20.92  4.08  Female     No   Sat  Dinner     2
105       15.36  1.64    Male    Yes   Sat  Dinner     2
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[143 rows x 7 columns]

In [ ]:
pd.concat((d1, d2), axis = 0)

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
pd.concat((d1,d2), axis = 1)

,total_bill,tip,sex,smoker,day,time,size,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,Female,No,Sun,Dinner,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,10.34,1.66,Male,No,Sun,Dinner,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,21.01,3.50,Male,No,Sun,Dinner,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,23.68,3.31,Male,No,Sun,Dinner,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,24.59,3.61,Female,No,Sun,Dinner,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29.03,5.92,Male,No,Sat,Dinner,3.0
240,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.18,2.00,Female,Yes,Sat,Dinner,2.0
241,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.67,2.00,Male,Yes,Sat,Dinner,2.0
242,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.82,1.75,Male,No,Sat,Dinner,2.0
243,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.78,3.00,Female,No,Thur,Dinner,2.0

In [ ]:
d1.merge(d2, how="left")

     total_bill   tip     sex smoker  day    time  size
0         16.99  1.01  Female     No  Sun  Dinner     2
1         10.34  1.66    Male     No  Sun  Dinner     3
2         21.01  3.50    Male     No  Sun  Dinner     3
3         23.68  3.31    Male     No  Sun  Dinner     2
4         24.59  3.61  Female     No  Sun  Dinner     4
..          ...   ...     ...    ...  ...     ...   ...
96        27.28  4.00    Male    Yes  Fri  Dinner     2
97        12.03  1.50    Male    Yes  Fri  Dinner     2
98        21.01  3.00    Male    Yes  Fri  Dinner     2
99        12.46  1.50    Male     No  Fri  Dinner     2
100       11.35  2.50  Female    Yes  Fri  Dinner     2

[101 rows x 7 columns]