<a href="https://colab.research.google.com/github/Deveshjd/ML-Notebooks/blob/main/working_with_datasets.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as mp
import pandas as pd
import seaborn as sns

In [ ]:
data = sns.load_dataset("tips")
data

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
data["sex"].shape[0]

244

In [ ]:
# How many male came on thursday
data[(data["sex"] == "Male") & (data["day"] == "Thur")].shape[0]

30

In [ ]:
# Average tip given by all males
data[data["sex"] == "Male"]["tip"].mean()

np.float64(3.0896178343949043)

In [ ]:
# No. of female smokers
data[(data["sex"] == "Female") & (data["smoker"] == "Yes")].shape[0]

33

In [ ]:
# Average size of female group
data[data["sex"] == "Female"]["size"].mean(). astype(int)

np.int64(2)

In [ ]:
# Average bill paid on sunday
data[data["day"] == "Sun"]["total_bill"].mean()

np.float64(21.41)

In [ ]:
# Highest bill ever paid for dinner
data[data["time"] == "Dinner"]["total_bill"].max()

50.81

In [ ]:
# Higest no. of smokers visited on which day
for i in data["day"].value_counts().index:
  print(f"{i} --> {data[(data["smoker"] == "Yes") & (data['day'] == i)].shape[0]}")

Sat --> 42
Sun --> 19
Thur --> 17
Fri --> 15

In [ ]:
# compare no. of females visited for lunch and dinner
for i in data["time"].value_counts().index:
  print(f"{i} --> {data[data["sex"] == "Female"].shape[0]}")

Dinner --> 87
Lunch --> 87

In [ ]:
# what time does the non smokers prefer(lunch, dinner)
for i in data["time"].value_counts().index:
  print(f"{i} --> {data[(data["smoker"] == "No") & (data["time"] == i)].shape[0]}")

Dinner --> 106
Lunch --> 45

In [ ]:
data[(data["sex"] == "Male") & (data["day" == "thu"])].value_counts()

In [ ]:
for i in data["day"].value_counts().index:
  print(f"{i} --> {data[(data["smoker"] == "Yes") & (data['day'] == i)].shape[0]}")

Sat --> 42
Sun --> 19
Thur --> 17
Fri --> 15

In [ ]:
data["size"].value_counts()

size
2    156
3     38
4     37
5      5
1      4
6      4
Name: count, dtype: int64

In [ ]:
# sabse zyada tip male ne di ya female ne

data[(data["sex"] == "Male") & (data["tip"] == data["tip"].max())]["tip"]

# data["tip"].max()

170    10.0
Name: tip, dtype: float64

In [ ]:
# sabse zyada smoking male ne kri ya female ne

for i in data["sex"].value_counts().index:
  print(f"{i} --> {data[(data["sex"] == i) & (data["smoker"] == "Yes")].shape[0]}")

Male --> 60
Female --> 33

# New Section

In [2]:
import numpy as np
import pandas as pd
# import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
data = sns.load_dataset("tips")
data.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [4]:
data["size"].value_counts()

size
2    156
3     38
4     37
5      5
1      4
6      4
Name: count, dtype: int64

In [17]:
data.shape

(244, 7)

In [5]:
data["size"].shape[0]

244

In [9]:
data["size"].value_counts().index

Index([2, 3, 4, 5, 1, 6], dtype='int64', name='size')

In [10]:
data["size"].value_counts().values

array([156,  38,  37,   5,   4,   4])

In [11]:
data["size"].value_counts().index[0]

np.int64(2)

In [15]:
data["size"].value_counts().shape[0]

6

In [26]:
# On which day most smokers come:

for i in data["day"].value_counts().index:
  print(f"{i} --> {data[(data['smoker'] == 'Yes') & (data["day"] == i)].shape[0]}")

Sat --> 42
Sun --> 19
Thur --> 17
Fri --> 15

In [28]:
data["day"].groupby(data["smoker"]).value_counts()

/tmp/ipykernel_6400/250512116.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  data["day"].groupby(data["smoker"]).value_counts()

smoker  day
Yes     Sat     42
        Sun     19
        Thur    17
        Fri     15
No      Sun     57
        Thur    45
        Sat     45
        Fri      4
Name: count, dtype: int64

In [32]:
# lazy evaluation
# eager eval
# iterator and generator

In [36]:
data.groupby("day").value_counts().index

/tmp/ipykernel_6400/1812901181.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  data.groupby("day").value_counts().index

MultiIndex([('Thur',  13.0,  2.0, 'Female', 'Yes',  'Lunch', 2),
            ('Thur',  7.51,  2.0,   'Male',  'No',  'Lunch', 2),
            ('Thur',  7.56, 1.44,   'Male',  'No',  'Lunch', 2),
            ('Thur',  8.35,  1.5, 'Female',  'No',  'Lunch', 2),
            ('Thur',  8.51, 1.25, 'Female',  'No',  'Lunch', 2),
            ('Thur',  8.52, 1.48,   'Male',  'No',  'Lunch', 2),
            ('Thur',  9.78, 1.73,   'Male',  'No',  'Lunch', 2),
            ('Thur', 10.07, 1.83, 'Female',  'No',  'Lunch', 1),
            ('Thur', 10.33,  2.0, 'Female',  'No',  'Lunch', 2),
            ('Thur', 10.34,  2.0,   'Male', 'Yes',  'Lunch', 2),
            ...
            ( 'Sun', 50.81, 10.0, 'Female',  'No',  'Lunch', 3),
            ( 'Sun', 50.81, 10.0, 'Female',  'No',  'Lunch', 4),
            ( 'Sun', 50.81, 10.0, 'Female',  'No',  'Lunch', 5),
            ( 'Sun', 50.81, 10.0, 'Female',  'No',  'Lunch', 6),
            ( 'Sun', 50.81, 10.0, 'Female',  'No', 'Dinner', 1),
            ( 'Sun', 50.81, 10.0, 'Female',  'No', 'Dinner', 2),
            ( 'Sun', 50.81, 10.0, 'Female',  'No', 'Dinner', 3),
            ( 'Sun', 50.81, 10.0, 'Female',  'No', 'Dinner', 4),
            ( 'Sun', 50.81, 10.0, 'Female',  'No', 'Dinner', 5),
            ( 'Sun', 50.81, 10.0, 'Female',  'No', 'Dinner', 6)],
           names=['day', 'total_bill', 'tip', 'sex', 'smoker', 'time', 'size'], length=5408064)

In [35]:
data.groupby(data["day"]).value_counts().index

/tmp/ipykernel_6400/1263220873.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  data.groupby(data["day"]).value_counts().index

MultiIndex([('Thur',  13.0,  2.0, 'Female', 'Yes',  'Lunch', 2),
            ('Thur',  7.51,  2.0,   'Male',  'No',  'Lunch', 2),
            ('Thur',  7.56, 1.44,   'Male',  'No',  'Lunch', 2),
            ('Thur',  8.35,  1.5, 'Female',  'No',  'Lunch', 2),
            ('Thur',  8.51, 1.25, 'Female',  'No',  'Lunch', 2),
            ('Thur',  8.52, 1.48,   'Male',  'No',  'Lunch', 2),
            ('Thur',  9.78, 1.73,   'Male',  'No',  'Lunch', 2),
            ('Thur', 10.07, 1.83, 'Female',  'No',  'Lunch', 1),
            ('Thur', 10.33,  2.0, 'Female',  'No',  'Lunch', 2),
            ('Thur', 10.34,  2.0,   'Male', 'Yes',  'Lunch', 2),
            ...
            ( 'Sun', 50.81, 10.0, 'Female',  'No',  'Lunch', 3),
            ( 'Sun', 50.81, 10.0, 'Female',  'No',  'Lunch', 4),
            ( 'Sun', 50.81, 10.0, 'Female',  'No',  'Lunch', 5),
            ( 'Sun', 50.81, 10.0, 'Female',  'No',  'Lunch', 6),
            ( 'Sun', 50.81, 10.0, 'Female',  'No', 'Dinner', 1),
            ( 'Sun', 50.81, 10.0, 'Female',  'No', 'Dinner', 2),
            ( 'Sun', 50.81, 10.0, 'Female',  'No', 'Dinner', 3),
            ( 'Sun', 50.81, 10.0, 'Female',  'No', 'Dinner', 4),
            ( 'Sun', 50.81, 10.0, 'Female',  'No', 'Dinner', 5),
            ( 'Sun', 50.81, 10.0, 'Female',  'No', 'Dinner', 6)],
           names=['day', 'total_bill', 'tip', 'sex', 'smoker', 'time', 'size'], length=5408064)

In [37]:
ind = data.groupby("day").groups
ind

/tmp/ipykernel_6400/3813916111.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ind = data.groupby("day").groups

{'Thur': [77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 243], 'Fri': [90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 220, 221, 222, 223, 224, 225, 226], 'Sat': [19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 168, 169, 170, 171, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242], 'Sun': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 112, 113, 114, 115, 116, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190]}

In [41]:
ind["Thur"]

Index([ 77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131,
       132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145,
       146, 147, 148, 149, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200,
       201, 202, 203, 204, 205, 243],
      dtype='int64')

In [43]:
data.iloc[ind["Thur"]]

     total_bill   tip     sex smoker   day    time  size
77        27.20  4.00    Male     No  Thur   Lunch     4
78        22.76  3.00    Male     No  Thur   Lunch     2
79        17.29  2.71    Male     No  Thur   Lunch     2
80        19.44  3.00    Male    Yes  Thur   Lunch     2
81        16.66  3.40    Male     No  Thur   Lunch     2
..          ...   ...     ...    ...   ...     ...   ...
202       13.00  2.00  Female    Yes  Thur   Lunch     2
203       16.40  2.50  Female    Yes  Thur   Lunch     2
204       20.53  4.00    Male    Yes  Thur   Lunch     4
205       16.47  3.23  Female    Yes  Thur   Lunch     3
243       18.78  3.00  Female     No  Thur  Dinner     2

[62 rows x 7 columns]

In [46]:
data.groupby("day")["tip"].mean()

/tmp/ipykernel_6400/3508396809.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  data.groupby("day")["tip"].mean()

day
Thur    2.771452
Fri     2.734737
Sat     2.993103
Sun     3.255132
Name: tip, dtype: float64

In [47]:
data.groupby("day")["tip"].agg(["mean", "median", "sum"])

/tmp/ipykernel_6400/4239739830.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  data.groupby("day")["tip"].agg(["mean", "median", "sum"])

          mean  median     sum
day
Thur  2.771452   2.305  171.83
Fri   2.734737   3.000   51.96
Sat   2.993103   2.750  260.40
Sun   3.255132   3.150  247.39

In [51]:
data.groupby("sex")["tip"].agg(["mean", "median", "sum"])

/tmp/ipykernel_6400/2245297363.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  data.groupby("sex")["tip"].agg(["mean", "median", "sum"])

            mean  median     sum
sex
Male    3.089618    3.00  485.07
Female  2.833448    2.75  246.51

In [52]:
data.groupby(["day", "size"])["tip"].mean()

/tmp/ipykernel_6400/1718758377.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  data.groupby(["day", "size"])["tip"].mean()

day   size
Thur  1       1.830000
      2       2.442500
      3       2.692500
      4       4.218000
      5       5.000000
      6       5.300000
Fri   1       1.920000
      2       2.644375
      3       3.000000
      4       4.730000
      5            NaN
      6            NaN
Sat   1       1.000000
      2       2.517547
      3       3.797778
      4       4.123846
      5       3.000000
      6            NaN
Sun   1            NaN
      2       2.816923
      3       3.120667
      4       4.087778
      5       4.046667
      6       5.000000
Name: tip, dtype: float64

In [53]:
data.groupby("day")["tip"].mean()

/tmp/ipykernel_6400/3508396809.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  data.groupby("day")["tip"].mean()

day
Thur    2.771452
Fri     2.734737
Sat     2.993103
Sun     3.255132
Name: tip, dtype: float64