<a href="https://colab.research.google.com/github/Deveshjd/ML-Notebooks/blob/main/Working_with_datasets3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [22]:
df = pd.DataFrame({
    "Name" : ["Dj", "Rj", "Vp", "Rs", "Hk", "ab", "cd", "ef", "gh", "hd"],
    "Age" : np.random.randint(20,40, 10),
    "Sex" : np.random.choice(["Male", "Female"], 10),
    "Marks" : np.random.normal(40,10,10),
    "Salary" : np.random.normal(100000,5000,10).astype(int),
    "Height" : np.random.randint(50,100,10)
})

In [24]:
df["Height"].map(lambda x : str(x) + " cm")

0    92 cm
1    67 cm
2    76 cm
3    94 cm
4    78 cm
5    55 cm
6    66 cm
7    78 cm
8    99 cm
9    75 cm
Name: Height, dtype: object

In [26]:
df["Height"]= df["Height"].map(lambda x : int(x.split()[0]))

SyntaxError: invalid syntax. Perhaps you forgot a comma? (437819143.py, line 1)

In [27]:
import seaborn as sns

In [28]:
data = sns.load_dataset("tips")

In [29]:
data

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [30]:
data["sex"]=data["sex"].map({"Male":0,"Female":1})

In [35]:
data["smoker"]=data["smoker"].map({"Yes":1,"No":0})

In [37]:
data["time"]=data["time"].map({"Dinner":0,"Lunch":1})

In [39]:
data["day"]=data["day"].map({"Thur":1,"Fri":2, "Sat":3,"Sun":4})

In [41]:
data["total_bill"]=data["total_bill"].round()

In [42]:
data

     total_bill   tip sex smoker day time  size
0          17.0  1.01   0      0   4    0     2
1          10.0  1.66   0      0   4    0     3
2          21.0  3.50   0      0   4    0     3
3          24.0  3.31   0      0   4    0     2
4          25.0  3.61   0      0   4    0     4
..          ...   ...  ..    ...  ..  ...   ...
239        29.0  5.92   0      0   3    0     3
240        27.0  2.00   1      1   3    0     2
241        23.0  2.00   1      1   3    0     2
242        18.0  1.75   0      0   3    0     2
243        19.0  3.00   0      0   1    0     2

[244 rows x 7 columns]